// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNfqCNk6sZiZy4_Ig0ficj1XxXPQpUF0',
    appId: '1:505213971307:web:9d54a3385f8245b3d87a2e',
    messagingSenderId: '505213971307',
    projectId: 'fir-app-68e41',
    authDomain: 'fir-app-68e41.firebaseapp.com',
    storageBucket: 'fir-app-68e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpXMdfeXtzUqioEQyb60zH-7s4xIKSAI',
    appId: '1:505213971307:ios:e3df6156001183a3d87a2e',
    messagingSenderId: '505213971307',
    projectId: 'fir-app-68e41',
    storageBucket: 'fir-app-68e41.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvpXMdfeXtzUqioEQyb60zH-7s4xIKSAI',
    appId: '1:505213971307:ios:e3df6156001183a3d87a2e',
    messagingSenderId: '505213971307',
    projectId: 'fir-app-68e41',
    storageBucket: 'fir-app-68e41.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSNfqCNk6sZiZy4_Ig0ficj1XxXPQpUF0',
    appId: '1:505213971307:web:9776d11da3ffd24cd87a2e',
    messagingSenderId: '505213971307',
    projectId: 'fir-app-68e41',
    authDomain: 'fir-app-68e41.firebaseapp.com',
    storageBucket: 'fir-app-68e41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27fK_Y7z2hACv2Q7aBgRg36WZRX5AeC8',
    appId: '1:505213971307:android:2525117f599754bfd87a2e',
    messagingSenderId: '505213971307',
    projectId: 'fir-app-68e41',
    storageBucket: 'fir-app-68e41.firebasestorage.app',
  );

}